server:
  port: 9000

spring:
  application:
    name: server-gateway
    serviceId: server-gateway

eureka:
  instance:
    hostname: localhost
    port: 17000
    preferIpAddress: true
    metadata-map:
      startup: ${random.int}
      # instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${spring.application.instance_id:${random.value}}:${server.port}
      #instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

reactive:
  feign:
    hystrix:
      enabled: false

synet:
  tcpservice:
    port: 7000
    readIdleTime: 60000
    writeIdleTime: 60000
  gatewayservice:
    routes:
      - id: server-logic
        uri: lb://server-logic
        order: 9000
        predicates:
        - Cmd=1
        - Cmd=2
        - Cmd=100~300

#logging:
#  level:
#    root: DEBUG