server:
  port: 9000

spring:
  application:
    name: server-gateway
    serviceId: server-gateway

eureka:
  instance:
    hostname: localhost
    port: 17000
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

greeting-other:
  ribbon:
    # the eureka vipAddress of the target service
    DeploymentContextBasedVipAddresses: server-logic

#logging:
#  level:
#    root: DEBUG