server:
  port: 9000

spring:
  application:
    name: server-gateway
    serviceId: server-gateway

eureka:
  instance:
    hostname: localhost
    port: 17000
    preferIpAddress: true
    metadata-map:
      startup: ${random.int}
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

reactive:
  feign:
    hystrix:
      enabled: false

#logging:
#  level:
#    root: DEBUG