server:
  port: 9000

spring:
  application:
    name: server-gateway
    serviceId: server-gateway

eureka:
  instance:
    hostname: localhost
    port: 17000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/