server:
  port: 8000

spring:
  application:
    name: server-logic
    serviceId: server-logic
  data:
    mongodb:
      host: 192.168.99.249
      database: test
      port: 27017
#      username: admin
#      password: admin

#  datasource:
#    url: jdbc:postgresql://192.168.99.249:5432/test
#    username: root
#    password: 6tfc^YHN
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false

#  spring.data.mongodb.host=localhost
#  spring.data.mongodb.database=admin
#  spring.data.mongodb.port=27017
#  spring.data.mongodb.username=admin
#  spring.data.mongodb.password=admin
reactive:
  feign:
    hystrix:
      enabled: false


eureka:
  instance:
    hostname: localhost
    port: 17000
    preferIpAddress: true
#    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/


dbconfig:
  host: 192.168.99.249
  port: 5432
  database: test
  username: root
  password: 6tfc^YHN

#logging:
#  level:
#    root: DEBUG