server:
  port: 8000

spring:
  application:
    name: server-logic
    serviceId: server-logic
  datasource:
    url: jdbc:postgresql://192.168.99.249:5432/test
    username: root
    password: 6tfc^YHN
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

eureka:
  instance:
    hostname: localhost
    port: 17000
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

#logging:
#  level:
#    root: DEBUG