server:
  port: 8000

spring:
  application:
    name: login-logic
    serviceId: login-logic
  data:
    mongodb:
      host: 192.168.99.211
      database: test
      port: 27018
  redis:
    host: 192.168.99.230
    port: 6379
    database: 0

reactive:
  feign:
    hystrix:
      enabled: false

## cache 配置
synet:
  cache:
    type: redis
    redis:
      time-to-live: 3h
      cache-null-values: false

eureka:
  instance:
    hostname: localhost
    port: 17000
    preferIpAddress: true
#    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

#logging:
#  level:
#    root: DEBUG